namespace PersonalLogManager.Service.Models
{
    public enum PersonalLogTemplate
    {
        Text,
        AccountActivation,
        AccountDeactivation,
        AccountDeletion,
        AccountDeletionRequest,
        AccountRegistration,
        AccountEmailAddressChange,
        AccountFeatureEnablement,
        AccountFeatureDisablement,
        AccountPasswordChange,
        AccountPersonalNameChange,
        AccountPhoneNumberAddition,
        AccountPhoneNumberChange,
        AccountPhoneNumberRemoval,
        AccountProfilePictureChange,
        AccountSubscriptionPurchase,
        AccountUsernameChange,
        BloodDonation,
        DeliveryReceival,
        InternshipApplicationSubmission,
        MealVoucherCardCreditation,
        OnlineReviewSubmission,
        OnlineStorePurchase,
        VideoUpload
    }
}
